Noritake display implementation
bleakdev/FreeRTOS-CompDev pull request #5
Opened 2020-05-11 10:13 UTC by bleakdev

Noritake display implementation

2020-05-11 11:22 UTC, jzych requested changes

2020-05-11 11:22 UTC, jzych commented on src/display.h
> +void displayInit();
dobrze by bylo dodac komentarze opisujace co dane funkcje robia i co jest ich wejsciem/wyjsciem

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +static void write(uint8_t data, uint8_t rs)
co to jest rs? nie boj sie uzywac dlugich nazw zmiennych

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +        if (value & i)
setPinValue(NORITAKE_SIO, value & i)

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    setPinValue(NORITAKE_STB, 0);
calosc wyglada jak prosty uart z chip select, nie da rady zaprzegnac do tego jednego peryferium?

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +        if (value & i)
setPinValue(NORITAKE_SIO, value & i)

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    setPinValue(NORITAKE_STB, PIN_LOW);
Jesli juz uzywasz PIN_LOW i PIN_HIGH to badz konsekwetny wszedzie (popraw write)

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    delay(54);
delayUs?

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    if (addr < 0x14)
jak zmienisz kolejnosc warunkow to nie bedziesz musial pisac podwojnych warunkow w else if

2020-05-11 11:22 UTC, jzych commented on src/delay.c
> +    delayMicroseconds(us);
mozesz uzywac vTaskDelay, wykorzystaj mozliwosci FreeRTOS i nie blokuj procesora na czas opoznienia, jesli jego czas trwania nie jest krytyczny dla wykonywanego zadania.

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    // Send 3 times command for 8-bit mode
dlaczego 3 razy?

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +    cmd(0x08);
adresy rejestrow mozesz napisac w define'ach w headerze, tak samo jak ich opcje wypelnienia np.
write(DISPLAY_SETTINGS, DISPLAY_ON | CURSOR_BLINK)

2020-05-11 11:22 UTC, jzych commented on src/display_noritake.c
> +        cmd(0x80 | 0x00 + x);
te wartosci mozesz zapisac w definach

2020-05-11 11:29 UTC, bleakdev commented on src/display_noritake.c
> +    // Send 3 times command for 8-bit mode
Tak trzeba przy manualnej inicjalizacji hd44780:
http://web.alfredstate.edu/faculty/weimandn/lcd/lcd_initialization/lcd_initialization_index.html
Jak przejdziesz do notes, zaczyna się od Step 2.

2020-05-11 17:12 UTC, jzych requested changes

2020-05-11 17:12 UTC, jzych commented on src/display_noritake.c
> +    delayUs(500);
tutaj i jeszcze w kilku miejscach uzywasz bardzo dlugich opoznien, ktore blokuja CPU. W tym czasie moglbyby dzialac inne zadania/processy, uzywaj vTaskDelay gdzie tylko sie da.

2020-05-11 17:12 UTC, jzych commented on src/display.h
> +#define DISPLAY_SET_COMMAND 0x38
Ewidentnie da sie te wartosci pogrupowac funkcjami czy rejestrami do ktorych sie odnosza, np DISPLAY ON i OFF powinny byc obok siebie.

2020-05-11 17:12 UTC, jzych commented on src/delay.c
> +    delayMicroseconds(us);
up

2020-05-11 17:12 UTC, jzych commented on src/display_noritake.c
> +    delayUs(54);
dlugi delay blokujacy CPU

2020-05-11 17:12 UTC, jzych commented on src/display_noritake.c
> +    delayUs(11000);
bardzo dlugi delay...

2020-05-12 06:34 UTC, jzych approved these changes

2020-05-12 06:38 UTC, merged