NRF24L01 implementation
bleakdev/FreeRTOS-CompDev pull request #9
Opened 2020-06-03 05:22 UTC by bleakdev

2020-06-04 12:12 UTC, jzych requested changes

2020-06-04 12:12 UTC, jzych commented on src/CompDevSDKMain.c
> +    nrf24Listen(0, address);
wrzuc calosc w recievierTask() dla lepszej czytelnosci

2020-06-04 12:12 UTC, jzych commented on src/CompDevSDKMain.c
> +#else
#elif TRANSMITER
ponieważ co jak nie ustawisz żadnej roli w Radio?

2020-06-04 12:12 UTC, jzych commented on src/CompDevSDKMain.c
> +    nrf24SetForTransmission(address);
całość wrzuć w transmiterTask()

2020-06-04 12:12 UTC, jzych commented on src/NRF24L01.c
> +    int success;
int success = -2; i brak ostatniego else i dopis w komentarzu ktory kod co oznacza

2020-06-04 12:12 UTC, jzych commented on src/NRF24L01.c
> +static void nrfInterruptTask(void *param)
moze nrfEventTask? albo cos ala EventHandle? sam kod sie nie dzieje w przerwaniu co moze byc mylace dla kogos z zewnatrz

2020-06-05 07:56 UTC, bleakdev commented on src/CompDevSDKMain.c
> +#else
Done (#elif dla #ifdef nie działa, ale zrobiłem po prostu else -> ifdef)

2020-06-05 07:56 UTC, bleakdev commented on src/CompDevSDKMain.c
> +    nrf24SetForTransmission(address);
Done

2020-06-05 07:56 UTC, bleakdev commented on src/NRF24L01.c
> +    int success;
Done

2020-06-05 07:56 UTC, bleakdev commented on src/NRF24L01.c
> +static void nrfInterruptTask(void *param)
Done

2020-06-05 07:57 UTC, bleakdev commented on src/CompDevSDKMain.c
> +    nrf24Listen(0, address);
Done

2020-06-05 11:57 UTC, jzych requested changes

2020-06-05 11:57 UTC, jzych commented on src/CompDevSDKMain.c
> +    uint8_t on = 0;
bool?

2020-06-05 11:57 UTC, jzych commented on src/CompDevSDKMain.c
> +    #else if RECEIVER
#elif

2020-06-05 12:20 UTC, bleakdev commented on src/CompDevSDKMain.c
> +    uint8_t on = 0;
Done.

2020-06-05 12:20 UTC, bleakdev commented on src/CompDevSDKMain.c
> +    #else if RECEIVER
Właśnie z elif mam problem
```
error: #elif with no expression
     #elif RECEIVER
```
dlatego zastosowałem "else if".

https://onlinegdb.com/B1UB_2wh8

2020-06-05 12:30 UTC, jzych commented on src/CompDevSDKMain.c
> +    #else if RECEIVER
w tej wersji nie sprawdzasz czy RECEIVIER istnieje tylko czy jego wartosc jest true/false
#ifdef y
....
#endif
#ifdef x
...
#endif

2020-06-05 12:32 UTC, bleakdev commented on src/CompDevSDKMain.c
> +    #else if RECEIVER
Ok, leci poprawka.

2020-06-05 12:43 UTC, jzych approved these changes

2020-06-05 12:45 UTC, merged